### ISSUE TITLE
How you prevent from update theta that we don't want to update

### ISSUE THREAD

**Issue by LinHungShi** [daerduoCarey/SpatialTransformerLayer#1]
Hi, I am curious how you prevent theta from updating them. For example, If I want to fix theta_1_1 = 0.5, I write it in the .proto: theta_1_1 = 0.5 in the st_param. However, when I was reading st_layer.cpp I can't figure out how you implement this function to fix the parameter because when you do the forwarding, you just use thetas from bottom[1], but the predefined thetas are stored in pre_defined_theta. Am I wrong?

**Comment by daerduoCarey** [comment]
Hello. I think you may want to refer to the code for the solvers for further explanation. But long story in short, thetas are the outputs/inputs of the layers. They are not the parameters that you want to optimize for. If you question is on how to prevent the other four out of the six theta values from changing, then the answer is simple. Refer to the definition for the STLayer and the layer before/below/prior to the layer. The layer before the STLayer will only generate two theta values as outputs and the STLayer will use the default values for the other four. So, that's why only the two theta values can be updated.

Free feel to ask more. Thanks for using my implementation.
