### ISSUE TITLE
.caffemodel for initialisation

### ISSUE THREAD

**Issue by Tushar-N** [daerduoCarey/SpatialTransformerLayer#9]
Hi,

When you trained your models, did you initialise the inception networks with imagenet-pretrained weights or did you train from scratch? I ask because in your solver.prototxt you load weights from "models/googlenet-bn-cub-st/init_googlenet_bn_cub_two_st.caffemodel". Could you share the .caffemodel that you used please?

Thank you.

**Comment by daerduoCarey** [comment]
If I remember correctly, I used the pretrained inception network from caffe model zoo. Since in the cub experiment, the network is quite large so it's pretty hard to train from the scratch. Hope this answer your question. 

For the example script, "init_googlenet_bn_cub_two_st.caffemodel" is the intermediate caffemodel that I generated in my experiment. Don't use that. My script just shows you how to use the layer and please replace it with your own pretrained model or officially released pretrained models from caffe model zoo or other resources.

Thank you.

**Comment by Tushar-N** [comment]
Got it, thank you!

**Comment by sunformoon** [comment]
@daerduoCarey 
Hi Kaichun, thank you so much for your efforts! I am wondering if you could share the pretrained models? like, init_CUB_googLeNet_ST_INC1_INC2.caffemodel, init_googlenet_bn_cub_two_st.caffemodel, etc.
Much appreciated!

Best,
Zhuotun
